// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HabitToggleController from "./habit_toggle_controller"
application.register("habit-toggle", HabitToggleController)

import ScheduleDaysController from "./schedule_days_controller"
application.register("schedule-days", ScheduleDaysController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)
